spring:
  main:
    web-application-type: servlet
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  profiles:
    active: prod

server:
  port: ${PORT:8081}

logging:
  level:
    org.springframework.web: DEBUG

app:
  extensions:
    defaults:
      - bat
      - cmd
      - com
      - cpl
      - exe
      - scr
      - js
    custom:
      max: 200
  upload:
    dir: ${user.home}/flow_uploads
